// <auto-generated />
using System;
using ApiSportsBoilerPlate.Data.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiSportsBoilerPlate.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20210202145407_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiSportsBoilerPlate.Data.Entity.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<long>("RowCreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RowCreatedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RowModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RowModifiedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("ApiSportsBoilerPlate.Data.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RowCreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RowCreatedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RowModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RowModifiedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("ApiSportsBoilerPlate.Data.Entity.PersonClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<long>("RowCreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RowCreatedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RowModifiedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RowModifiedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonClub");
                });

            modelBuilder.Entity("ApiSportsBoilerPlate.Data.Entity.PersonClub", b =>
                {
                    b.HasOne("ApiSportsBoilerPlate.Data.Entity.Club", "Club")
                        .WithMany("PersonClub")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSportsBoilerPlate.Data.Entity.Person", "Person")
                        .WithMany("PersonClub")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
